version: '3.7'

services: 
  rabbitmq:
    image: docker.io/library/rabbitmq:3.8.14-management-alpine
    container_name: catalog-rabbitmq
    hostname: rabbitmq
    ports: 
      - 15672:15672
      - 5672:5672
    labels: 
      - io.podman.compose.project=catalogapi
    volumes: 
      - ./rabbitmqdata:/var/lib/rabbitmq:Z
    environment: 
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
