FROM docker.io/library/node:14.16.0-alpine3.11

WORKDIR /opt/app-root/

ENV PATH /opt/app-root/node_modules/.bin:$PATH

RUN chown -R 1001:0 /opt/app-root/ && chmod -R ug+rwx /opt/app-root/

# Add application sources
ADD . .

# Install the dependencies
RUN npm install

EXPOSE 3333

# Run script uses standard ways to run the application
CMD npm run start:dev

USER 1001
